#
# TABLE: rest_api_rate_limit
#
CREATE TABLE rest_api_rate_limit (client VARCHAR(255) NOT NULL DEFAULT "",
_group VARCHAR(255) NOT NULL DEFAULT "_ip_address", start TIMESTAMP NOT NULL DEFAULT
CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, count INT(11) NOT NULL DEFAULT 1,
PRIMARY KEY (client, group)) ENGINE=InnoDB;
